# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'shoot-report-ios_v3' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for shoot-report-ios_v3
	pod 'AAInfographics', :git => 'https://github.com/AAChartModel/AAChartKit-Swift.git'

  target 'shoot-report-ios_v3Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'shoot-report-ios_v3UITests' do
    # Pods for testing
  end

end
